# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/protobuf" # Location of package manifests
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 10
    groups:
      protobuf-plugins:
        patterns:
          - "kr.motd.maven:os-maven-plugin"
          - "org.codehaus.mojo:build-helper-maven-plugin"
          - "org.xolstice.maven.plugins:protobuf-maven-plugin"
      standard-plugins:
        patterns:
          - "com.google.code.maven-replacer-plugin:maven-replacer-plugin"
      dependencies:
        patterns:
          - "com.google.protobuf*"
    ignore:
      - dependency-name: "org.codehaus.plexus:plexus-utils"
        update-types: ["version-update:semver-major","version-update:semver-minor"]
          
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 10
    groups:
      standard-plugins:
        patterns:
          - "org.codehaus.mojo:flatten-maven-plugin"
          - "org.apache.maven.plugins*"
      dependencies:
        patterns:
          - "gov.hhs.aspr.ms:util"
          - "com.google.code.gson:gson"
      test-dependencies:
        patterns:
          - "org.jacoco*"
          - "org.junit.jupiter*"
    ignore:
      - dependency-name: "org.codehaus.plexus:plexus-utils"
        update-types: ["version-update:semver-major","version-update:semver-minor"]
