crossref:
  lst-title: 'Code Block'
  fig-title: "Figure"
  lst-prefix: 'Code Block'
##  title-delim: ""
##  labels: arabic
##  lst-labels: arabic
project:
  type: book
  output-dir: docs   #Change to redirect where compiled html pages are saved upon rendering
documentclass: book
language: 
  ui:
    chapter_name: "Chapter"
##biblio-style: apalike
##link-citations: true
##colorlinks: true
#lot: true  #- only for PDF
#lof: true  #- only for PDF
book:
  title: "Taskit-Docs"
  author: "HHS ASPR Modeling Group"
  date: "04/15/2025"
  chapters:
    - index.qmd
    - ch01-Introduction.qmd
    - ch02-CoreLibrary.qmd
    - ch03-ProtobufLibrary.qmd
##bibliography: references.bib
format:
  html:
    toc-depth: 4
    toc-expand: 3
    syntax-definitions: 
      - java.xml
    code-line-numbers: true
#    code-fold: show
    number-sections: true
    number-depth: 5
    css: styles.css
    global-numbering: true
    fig-cap-location: top
    fig-format: svg
    fig-align: center
    #highlight-style: nord
    #highlight-style: oblivion
    theme: cosmo
editor: visual

